# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-20 02:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organisasi',
            fields=[
                ('email_organisasi', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('website', models.CharField(max_length=50)),
                ('nama', models.CharField(max_length=50)),
                ('provinsi', models.CharField(max_length=50)),
                ('kabupaten_kota', models.CharField(max_length=50)),
                ('kecamatan', models.CharField(max_length=50)),
                ('kelurahan', models.CharField(max_length=50)),
                ('kode_pos', models.CharField(max_length=50)),
                ('status_verifikasi', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'organisasi',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('email', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('nama', models.CharField(max_length=100)),
                ('alamat_lengkap', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'USER',
            },
        ),
        migrations.CreateModel(
            name='Donatur',
            fields=[
                ('email', models.ForeignKey(db_column='email', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='login.User')),
                ('saldo', models.IntegerField()),
            ],
            options={
                'db_table': 'donatur',
            },
        ),
        migrations.CreateModel(
            name='Relawan',
            fields=[
                ('email', models.ForeignKey(db_column='email', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='login.User')),
                ('no_hp', models.CharField(max_length=20)),
                ('tanggal_lahir', models.DateField()),
            ],
            options={
                'db_table': 'relawan',
            },
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('email', models.ForeignKey(db_column='email', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='login.User')),
                ('logo_sponsor', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'sponsor',
            },
        ),
    ]
