# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-19 23:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organisasi',
            fields=[
                ('email_organisasi', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('website', models.CharField(max_length=50)),
                ('nama', models.CharField(max_length=50)),
                ('provinsi', models.CharField(max_length=50)),
                ('kabupaten_kota', models.CharField(max_length=50)),
                ('kecamatan', models.CharField(max_length=50)),
                ('kelurahan', models.CharField(max_length=50)),
                ('kode_pos', models.CharField(max_length=50)),
                ('status_verifikasi', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'organisasi',
            },
        ),
        migrations.AlterUniqueTogether(
            name='keahlian_relawan',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='keahlian_relawan',
            name='email',
        ),
        migrations.AlterModelOptions(
            name='donatur',
            options={},
        ),
        migrations.AlterModelOptions(
            name='relawan',
            options={},
        ),
        migrations.AlterModelOptions(
            name='sponsor',
            options={},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.DeleteModel(
            name='Keahlian_relawan',
        ),
    ]
