# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-19 23:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0002_auto_20180520_0654'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganisasiTerverifikasi',
            fields=[
                ('email_organisasi', models.ForeignKey(db_column='email_organisasi', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='login.Organisasi')),
                ('nomor_registrasi', models.CharField(max_length=50)),
                ('status_aktif', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'organisasi_terverifikasi',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PengurusOrganisasi',
            fields=[
                ('email', models.ForeignKey(db_column='email', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='login.User')),
            ],
            options={
                'db_table': 'pengurus_organisasi',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TujuanOrganisasi',
            fields=[
                ('organisasi', models.ForeignKey(db_column='organisasi', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='login.Organisasi')),
                ('tujuan', models.TextField()),
            ],
            options={
                'db_table': 'tujuan_organisasi',
                'managed': False,
            },
        ),
    ]
