# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-20 02:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonaturOrganisasi',
            fields=[
                ('donatur', models.ForeignKey(db_column='donatur', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='login.Donatur')),
                ('tanggal', models.DateField()),
                ('nominal', models.IntegerField()),
            ],
            options={
                'db_table': 'donatur_organisasi',
            },
        ),
        migrations.CreateModel(
            name='OrganisasiTerverifikasi',
            fields=[
                ('email_organisasi', models.ForeignKey(db_column='email_organisasi', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='login.Organisasi')),
                ('nomor_registrasi', models.CharField(max_length=50)),
                ('status_aktif', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'organisasi_terverifikasi',
            },
        ),
        migrations.CreateModel(
            name='PengurusOrganisasi',
            fields=[
                ('email', models.ForeignKey(db_column='email', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='login.User')),
            ],
            options={
                'db_table': 'pengurus_organisasi',
            },
        ),
        migrations.CreateModel(
            name='SponsorOrganisasi',
            fields=[
                ('sponsor', models.ForeignKey(db_column='sponsor', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='login.Sponsor')),
                ('tanggal', models.DateField()),
                ('nominal', models.IntegerField()),
                ('organisasi', models.ForeignKey(db_column='organisasi', on_delete=django.db.models.deletion.DO_NOTHING, to='profil_organisasi.OrganisasiTerverifikasi')),
            ],
            options={
                'db_table': 'sponsor_organisasi',
            },
        ),
        migrations.CreateModel(
            name='TujuanOrganisasi',
            fields=[
                ('organisasi', models.ForeignKey(db_column='organisasi', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='login.Organisasi')),
                ('tujuan', models.TextField()),
            ],
            options={
                'db_table': 'tujuan_organisasi',
            },
        ),
        migrations.AlterUniqueTogether(
            name='tujuanorganisasi',
            unique_together=set([('organisasi', 'tujuan')]),
        ),
        migrations.AddField(
            model_name='pengurusorganisasi',
            name='organisasi',
            field=models.ForeignKey(db_column='organisasi', on_delete=django.db.models.deletion.DO_NOTHING, to='login.Organisasi'),
        ),
        migrations.AddField(
            model_name='donaturorganisasi',
            name='organisasi',
            field=models.ForeignKey(db_column='organisasi', on_delete=django.db.models.deletion.DO_NOTHING, to='profil_organisasi.OrganisasiTerverifikasi'),
        ),
        migrations.AlterUniqueTogether(
            name='sponsororganisasi',
            unique_together=set([('sponsor', 'organisasi')]),
        ),
        migrations.AlterUniqueTogether(
            name='donaturorganisasi',
            unique_together=set([('donatur', 'organisasi')]),
        ),
    ]
